### ISSUE TITLE
cpanel-ea4-force-php-opts not working

### ISSUE THREAD

**Issue by dancandale** [macklus/cpanel-ea4-force-php-opts#1] opened 2017-12-27 14:20 UTC
Hello,

I try to implement the solution on a cpanel server ( EA4+suphp) but is not working.

I find your solution very useful. Hope you find the issue.

Thank you.

**Comment by macklus** [comment] 2017-12-28 08:19
hi!
can you provide more info, a modified php.ini file or something ? 
i run some test, but find nothing

**Comment by dancandale** [comment] 2017-12-28 08:50
Hi,

I have installed "cpanel-ea4-force-php-opts" as in the documentation, then restart apache service.

I expect that "open_basedir" for all users to be "/home/userx:/usr/lib/php:/usr/local/lib/php"  given that "__HOME__" variable applies to each user individually.

I have not edited at all the /etc/apache2/cpanel-ea4-force-php-opts.conf , its look like in Sample file.


I'm missing something?

Thank you.

**Comment by dancandale** [comment] 2017-12-28 09:36
Hi!

Ok, I am sorry, the patch is working well but it updates only when create or remove an cpanel account by:

Whostmgr::Accounts::Create
or
Whostmgr::Accounts::Remove

Last question, It is a way to update otherwise? by running a command or something? Because when exclude an user I need to create/remove an account to make the change :)

Thank you again.

**Comment by dancandale** [comment] 2017-12-28 10:15
I figured out how to do it the manual update, by runing the script: /usr/local/cpanel/scripts/cpanel-ea4-force-php-opts

But I see that the patch does not work on the litespeed webserver ( cpanel plugin ) do you have any idea why?

**Comment by macklus** [comment] 2017-12-30 17:11
Never use litespeed server on cpanel, so i not sure whats the problem is about.

Even that, the first step i do was create a phpinfo.php file in one server account), who contains:
```
<?php
phpinfo();
```

when you open it in a navigator, you can see which ini files are php using. If this are diferent due this plugin, let me know and i update the script

**Comment by dancandale** [comment] 2018-01-03 12:22
Hi,

Litespeed Support team confirm that have an issues with .ini files read in this issue. So will be solve in the next update of LSWS. Aftfer that your plugin will be compatible with Litespeed.

Thank you for the support.

**Comment by macklus** [comment] 2018-01-05 09:30
Close the issue.
thank you for the report.

**Closed as completed by macklus** 2018-01-05 09:30 UTC
Labels: enhancement, question
